---
tools_dir: /opt
home_dir: ~

dev_users:
  - name: marco
    comment: "Marco Lancini"
    shell: /bin/bash

# dev_user_keys:
#   - name: marco
#     ssh_key: "ssh-rsa ..."

#dev_make_dirs:

dev_apt:
  - mlocate
  - zsh
  - ufw
  - bash-completion

#dev_pip:

#dev_easy_install:

#dev_gem:

#dev_go:

#dev_go_build:

#dev_git_repositories:

#dev_shortcuts:

dev_binary:
  - url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/zsh-installer.sh
  - url: https://raw.githubusercontent.com/ahmetb/kubectl-aliases/master/.kubectl_aliases
    dest: "{{ home_dir }}/.kubectl_aliases"

dev_tars:
  - src: https://github.com/mbadolato/iTerm2-Color-Schemes/archive/master.zip
    dest: "/tmp/iTerm2-Color-Schemes/"

dev_config:
  - src: custom.zsh-theme
    dest: "{{ home_dir }}/.oh-my-zsh/themes/custom.zsh-theme"

dev_templates:
  - src: ssh_config.j2
    dest: /etc/
    mode: "0644"
  - src: zshrc.j2
    dest: /root/.zshrc
    mode: "0644"

dev_bash:
  - bash.sh
